sudo: required
services:
  - docker

before_install:
  - docker build -t ofovweewere/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ofovweewere/react-test npm run test

after_success:
  - docker build -t ofovweewere/multi-client ./client
  - docker build -t ofovweewere/multi-nginx ./nginx
  - docker build -t ofovweewere/multi-server ./server
  - docker build -t ofovweewere/multi-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ca-central-1-355782294313"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
